name: whatforwhere
channels: 
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pandas=2.2.1
  - numpy=1.26.4
  - dask=2024.3.1
  - matplotlib=3.8.0
  - scikit-learn=1.3.0
  - cloudpickle=3.0.0
  - lz4=4.3.3
  - toolz=0.12.1
  - tornado=6.4
  - pip
  - pip:
    - msgpack==1.0.8
